# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 206)
        self.pp1 = QtWidgets.QLabel(Form)
        self.pp1.setGeometry(QtCore.QRect(30, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp1.setFont(font)
        self.pp1.setAlignment(QtCore.Qt.AlignCenter)
        self.pp1.setObjectName("pp1")
        self.pp2 = QtWidgets.QLabel(Form)
        self.pp2.setGeometry(QtCore.QRect(160, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp2.setFont(font)
        self.pp2.setAlignment(QtCore.Qt.AlignCenter)
        self.pp2.setObjectName("pp2")
        self.pp3 = QtWidgets.QLabel(Form)
        self.pp3.setGeometry(QtCore.QRect(290, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp3.setFont(font)
        self.pp3.setAlignment(QtCore.Qt.AlignCenter)
        self.pp3.setObjectName("pp3")
        self.p3 = QtWidgets.QListWidget(Form)
        self.p3.setGeometry(QtCore.QRect(290, 80, 91, 41))
        self.p3.setObjectName("p3")
        item = QtWidgets.QListWidgetItem()
        self.p3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.p3.addItem(item)
        self.p1 = QtWidgets.QTextEdit(Form)
        self.p1.setGeometry(QtCore.QRect(30, 80, 91, 81))
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QTextEdit(Form)
        self.p2.setGeometry(QtCore.QRect(160, 80, 91, 81))
        self.p2.setObjectName("p2")
        self.pp4 = QtWidgets.QLabel(Form)
        self.pp4.setGeometry(QtCore.QRect(410, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp4.setFont(font)
        self.pp4.setAlignment(QtCore.Qt.AlignCenter)
        self.pp4.setObjectName("pp4")
        self.p4 = QtWidgets.QTextEdit(Form)
        self.p4.setGeometry(QtCore.QRect(410, 80, 91, 81))
        self.p4.setObjectName("p4")
        self.pp5 = QtWidgets.QLabel(Form)
        self.pp5.setGeometry(QtCore.QRect(540, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp5.setFont(font)
        self.pp5.setAlignment(QtCore.Qt.AlignCenter)
        self.pp5.setObjectName("pp5")
        self.pp6 = QtWidgets.QLabel(Form)
        self.pp6.setGeometry(QtCore.QRect(670, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pp6.setFont(font)
        self.pp6.setAlignment(QtCore.Qt.AlignCenter)
        self.pp6.setObjectName("pp6")
        self.p5 = QtWidgets.QLineEdit(Form)
        self.p5.setGeometry(QtCore.QRect(540, 80, 91, 20))
        self.p5.setObjectName("p5")
        self.p6 = QtWidgets.QLineEdit(Form)
        self.p6.setGeometry(QtCore.QRect(670, 80, 91, 20))
        self.p6.setObjectName("p6")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(644, 152, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save.setFont(font)
        self.save.setObjectName("save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pp1.setText(_translate("Form", "Name"))
        self.pp2.setText(_translate("Form", "Bake"))
        self.pp3.setText(_translate("Form", "Type"))
        __sortingEnabled = self.p3.isSortingEnabled()
        self.p3.setSortingEnabled(False)
        item = self.p3.item(0)
        item.setText(_translate("Form", "Молотый"))
        item = self.p3.item(1)
        item.setText(_translate("Form", "В зернах"))
        self.p3.setSortingEnabled(__sortingEnabled)
        self.pp4.setText(_translate("Form", "Description"))
        self.pp5.setText(_translate("Form", "Price"))
        self.pp6.setText(_translate("Form", "Pack Volume"))
        self.save.setText(_translate("Form", "Save"))

    def get_objects(self):
        return self.p1, self.p2, self.p3, self.p4, self.p5, self.p6, self.save