# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 598)
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(480, 550, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.view = QtWidgets.QTableWidget(Form)
        self.view.setGeometry(QtCore.QRect(0, 0, 729, 551))
        self.view.setObjectName("view")
        self.view.setColumnCount(0)
        self.view.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add.setText(_translate("Form", "Добавить/изменить кофе"))

    def get_objects(self):
        return self.add, self.view